import Login from 'Components/Login/Login'
import Head from 'next/head'
import { getSession, useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

export default function Home() {

  // const {data:session} = useSession()

  // console.log(session);

  return (
    <>
      <Head>
        <title>Green-Fields</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login/>
      </main>
    </>
  )
}

export async function getServerSideProps(context){
  const session = await getSession ({
    req: context.req
  })

  if(session){
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false
      }
    }
  }
    return {
      props: { session}
    }
  }